package project;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import common.OpenPdf;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;

import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Lenovo
 */
public class Orders extends javax.swing.JFrame {
    
    private int customer_id = 0;
    private int product_id = 0;
    private int order_id = 0;
    private double final_total_price = 0;
    private String order_code = "";
    DefaultTableModel product_model;
    DefaultTableModel customer_model;
    Connection con;
    private  String username=" ";
    
    public Orders(String user) {
        initComponents();
        username = user;
        setLocationRelativeTo(null);
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Factory", "root", "root");
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        getDB();
        
    }
    
    public void clearProductFeilds() {
        product_id = 0;
        productName_edt_txt.setText("");
        price_edt_txt.setText("");
        ordersQuantity_edt_txt.setText("");
    }
    
    public String getUniqueId(String prefix) {
        
        return prefix + System.nanoTime();
    }
    
    public void getDB() {
        
        customer_model = (DefaultTableModel) cus_table.getModel();
        product_model = (DefaultTableModel) product_table.getModel();
        
        try {
            PreparedStatement stmt = con.prepareStatement("select Customer_id , Firstname,Lastname,Address,Phonenumber from customers");
            ResultSet rs = stmt.executeQuery();
            
            while (rs.next()) {
                customer_model.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(5), rs.getString(4)});
            }
            
            stmt = con.prepareStatement("select Product_Id,Name,Quantity,selling_price from products");
            rs = stmt.executeQuery();
            while (rs.next()) {
                product_model.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getDouble(4), rs.getString(3)});
                
            }
            
        } catch (Exception e) {
            System.out.println(e);
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cus_table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        firstN_edt_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lastN_edt_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        phNum_edt_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        address_edt_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        product_table = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        productName_edt_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        price_edt_txt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cart_table = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        totAmount_edt_txt = new javax.swing.JTextField();
        order_btn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        ordersQuantity_edt_txt = new javax.swing.JTextField();
        viewOrders_btn = new javax.swing.JButton();
        addToCart_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(213, 222, 239));

        jLabel1.setBackground(new java.awt.Color(213, 222, 239));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(57, 88, 134));
        jLabel1.setText("Place & Manage orders");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        cus_table.setBackground(new java.awt.Color(213, 222, 239));
        cus_table.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cus_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Phone Number", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cus_table.setShowGrid(true);
        cus_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cus_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cus_table);

        jLabel2.setBackground(new java.awt.Color(213, 222, 239));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(57, 88, 134));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/icons/icons8-customers-25.png"))); // NOI18N
        jLabel2.setText("Customer list");

        jLabel3.setBackground(new java.awt.Color(213, 222, 239));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(57, 88, 134));
        jLabel3.setText("First name");

        firstN_edt_txt.setEditable(false);
        firstN_edt_txt.setBackground(new java.awt.Color(240, 243, 250));
        firstN_edt_txt.setToolTipText("");

        jLabel4.setBackground(new java.awt.Color(213, 222, 239));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(57, 88, 134));
        jLabel4.setText("last name");

        lastN_edt_txt.setEditable(false);
        lastN_edt_txt.setBackground(new java.awt.Color(240, 243, 250));
        lastN_edt_txt.setToolTipText("");

        jLabel5.setBackground(new java.awt.Color(213, 222, 239));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(57, 88, 134));
        jLabel5.setText("Phone number");

        phNum_edt_txt.setEditable(false);
        phNum_edt_txt.setBackground(new java.awt.Color(240, 243, 250));
        phNum_edt_txt.setToolTipText("");

        jLabel6.setBackground(new java.awt.Color(213, 222, 239));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(57, 88, 134));
        jLabel6.setText("Address");

        address_edt_txt.setEditable(false);
        address_edt_txt.setBackground(new java.awt.Color(240, 243, 250));
        address_edt_txt.setToolTipText("");

        jLabel7.setBackground(new java.awt.Color(213, 222, 239));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(57, 88, 134));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/icons/product.png"))); // NOI18N
        jLabel7.setText("Product list");

        product_table.setBackground(new java.awt.Color(213, 222, 239));
        product_table.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        product_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Selling Price", "Avaliable in stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        product_table.setShowGrid(true);
        product_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(product_table);

        jLabel8.setBackground(new java.awt.Color(213, 222, 239));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(57, 88, 134));
        jLabel8.setText("Product name");

        productName_edt_txt.setEditable(false);
        productName_edt_txt.setBackground(new java.awt.Color(240, 243, 250));
        productName_edt_txt.setToolTipText("");
        productName_edt_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productName_edt_txtActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(213, 222, 239));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(57, 88, 134));
        jLabel9.setText("Product price");

        price_edt_txt.setEditable(false);
        price_edt_txt.setBackground(new java.awt.Color(240, 243, 250));
        price_edt_txt.setToolTipText("");

        jLabel11.setBackground(new java.awt.Color(213, 222, 239));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(57, 88, 134));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/icons/Cart.png"))); // NOI18N
        jLabel11.setText("Cart");

        cart_table.setBackground(new java.awt.Color(213, 222, 239));
        cart_table.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cart_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product_ID", "Name", "Quantity", "Price / unit", "Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cart_table.setShowGrid(true);
        cart_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cart_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(cart_table);

        jLabel12.setBackground(new java.awt.Color(213, 222, 239));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(57, 88, 134));
        jLabel12.setText("Total Amount");

        totAmount_edt_txt.setEditable(false);
        totAmount_edt_txt.setBackground(new java.awt.Color(240, 243, 250));
        totAmount_edt_txt.setToolTipText("");
        totAmount_edt_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totAmount_edt_txtActionPerformed(evt);
            }
        });

        order_btn.setBackground(new java.awt.Color(57, 88, 134));
        order_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        order_btn.setForeground(new java.awt.Color(213, 222, 239));
        order_btn.setText("Save order Details");
        order_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order_btnActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(213, 222, 239));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(57, 88, 134));
        jLabel10.setText("Order Quantity");

        ordersQuantity_edt_txt.setBackground(new java.awt.Color(240, 243, 250));
        ordersQuantity_edt_txt.setToolTipText("");

        viewOrders_btn.setBackground(new java.awt.Color(57, 88, 134));
        viewOrders_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewOrders_btn.setForeground(new java.awt.Color(213, 222, 239));
        viewOrders_btn.setText("View orders");
        viewOrders_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrders_btnActionPerformed(evt);
            }
        });

        addToCart_btn.setBackground(new java.awt.Color(57, 88, 134));
        addToCart_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addToCart_btn.setForeground(new java.awt.Color(213, 222, 239));
        addToCart_btn.setText("Add to Cart");
        addToCart_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCart_btnActionPerformed(evt);
            }
        });

        back_btn.setBackground(new java.awt.Color(57, 88, 134));
        back_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back_btn.setForeground(new java.awt.Color(213, 222, 239));
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(213, 222, 239));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(57, 88, 134));
        jLabel13.setText("Selected product");

        jLabel14.setBackground(new java.awt.Color(213, 222, 239));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(57, 88, 134));
        jLabel14.setText("Selected customer");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(57, 88, 134));
        jLabel15.setText("* select a row to remove a product");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(back_btn)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(24, 24, 24)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstN_edt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastN_edt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phNum_edt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(address_edt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel14)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(150, 150, 150)
                            .addComponent(jLabel7))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addToCart_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ordersQuantity_edt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(price_edt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(productName_edt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(order_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                            .addComponent(viewOrders_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totAmount_edt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2, jScrollPane3});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(totAmount_edt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(order_btn)
                        .addGap(18, 18, 18)
                        .addComponent(viewOrders_btn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(firstN_edt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(lastN_edt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(phNum_edt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(address_edt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(addToCart_btn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(productName_edt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(price_edt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(ordersQuantity_edt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(19, 19, 19)
                .addComponent(back_btn)
                .addGap(20, 20, 20))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2, jScrollPane3});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productName_edt_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productName_edt_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productName_edt_txtActionPerformed

    private void totAmount_edt_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totAmount_edt_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totAmount_edt_txtActionPerformed

    private void viewOrders_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrders_btnActionPerformed
        // TODO add your handling code here:
        new ViewOrders().setVisible(true);
        
        
    }//GEN-LAST:event_viewOrders_btnActionPerformed

    private void addToCart_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCart_btnActionPerformed
        // TODO add your handling code here:

        String orderedUnits = ordersQuantity_edt_txt.getText();
        if (!orderedUnits.isBlank()&&orderedUnits.matches("\\d+")) {
            
            String productName = productName_edt_txt.getText();
            String productPrice = price_edt_txt.getText();
            double totalPrice = Integer.parseInt(orderedUnits) * Double.parseDouble(productPrice);
            int checkStock = 0;
            int checkProductAlreadyInCart = 0;
            
            try {
                
                PreparedStatement st = con.prepareStatement("select *from products where Product_Id=" + product_id + "");
                ResultSet rs = st.executeQuery();
                while (rs.next()) {
                    //compares the quantity of stock products in the DB with the ordered quantity
                    if (rs.getInt(3) >= Integer.parseInt(orderedUnits)) {
                        
                        checkStock = 1;
                    } else {
                        JOptionPane.showMessageDialog(null, "Only " + rs.getInt(3) + " items left for the product\nPlease change the quantity");
                    }
                }
            } catch (Exception e) {
                System.out.println(e);
            }

            //checkProductAlreadyInCart
            if (checkStock == 1) {
                DefaultTableModel model = (DefaultTableModel) cart_table.getModel();
                if (cart_table.getRowCount() != 0) {
                    for (int i = 0; i < cart_table.getRowCount(); i++) {
                        if (Integer.parseInt(model.getValueAt(i, 0).toString()) == product_id) {
                            checkProductAlreadyInCart = 1;
                            JOptionPane.showMessageDialog(null, "Product Already exists in cart");
                        }
                    }
                }
                if (checkProductAlreadyInCart == 0) {
                    model.addRow(new Object[]{product_id, productName, orderedUnits,Double.parseDouble(productPrice), totalPrice});
                    final_total_price += totalPrice;
                    totAmount_edt_txt.setText(Double.toString(final_total_price));
                    JOptionPane.showMessageDialog(null, "Product is added successfully!");
                }
                clearProductFeilds();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a product and quantity ordered in numbers");
        }
        

    }//GEN-LAST:event_addToCart_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        new DashBoard(username).setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void cus_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cus_tableMouseClicked
        // TODO add your handling code here:
        int index = cus_table.getSelectedRow();
        TableModel model = cus_table.getModel();
        String id = model.getValueAt(index, 0).toString();
        customer_id = Integer.parseInt(id);
        firstN_edt_txt.setText(model.getValueAt(index, 1).toString());
        lastN_edt_txt.setText(model.getValueAt(index, 2).toString());
        phNum_edt_txt.setText(model.getValueAt(index, 3).toString());
        address_edt_txt.setText(model.getValueAt(index, 4).toString());
    }//GEN-LAST:event_cus_tableMouseClicked

    private void product_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_tableMouseClicked
        // TODO add your handling code here:
        int index = product_table.getSelectedRow();
        TableModel model = product_table.getModel();
        String id = model.getValueAt(index, 0).toString();
        product_id = Integer.parseInt(id);
        productName_edt_txt.setText(model.getValueAt(index, 1).toString());
        price_edt_txt.setText(model.getValueAt(index, 2).toString());
    }//GEN-LAST:event_product_tableMouseClicked

    private void cart_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cart_tableMouseClicked
        // TODO add your handling code here:
        int index = cart_table.getSelectedRow();
        int isRemoved = JOptionPane.showConfirmDialog(null, "Do you want to remove this product ?", "select", JOptionPane.YES_NO_OPTION);
        if (isRemoved == 0) {
            TableModel model = cart_table.getModel();
            String total = model.getValueAt(index, 3).toString();
            final_total_price -= Double.parseDouble(total);
            totAmount_edt_txt.setText(Double.toString(final_total_price));
            ((DefaultTableModel) cart_table.getModel()).removeRow(index);
        }
    }//GEN-LAST:event_cart_tableMouseClicked

    private void order_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order_btnActionPerformed
        // TODO add your handling code here:

        if (final_total_price != 0 && !firstN_edt_txt.getText().isEmpty()) {
            
            order_code = getUniqueId("Bill-");
            //updating orders DB
            DefaultTableModel dtm = (DefaultTableModel) cart_table.getModel();
            if (cart_table.getRowCount() != 0) {
                
                for (int i = 0; i < cart_table.getRowCount(); i++) {
                    try {
                        //subtracts the ordered quantites from the stocked quantites in Db
                        PreparedStatement stmt = con.prepareStatement("update products set Quantity = Quantity-" + Integer.parseInt(dtm.getValueAt(i, 2).toString()) + " where Product_Id=" + Integer.parseInt(dtm.getValueAt(i, 0).toString()));
                        stmt.executeUpdate();
                    } catch (Exception e) {
                        System.out.println(e);
                        JOptionPane.showMessageDialog(null, "orders DB\n"+e);
                    }
                }
            }
            
            try {
                //insert int orders db
                SimpleDateFormat myFormat = new SimpleDateFormat("dd-MM-yyyy");
                Calendar cal = Calendar.getInstance();
                PreparedStatement stmt = con.prepareStatement("insert into orders(order_code,customer_id,order_date,total_paid) values(?,?,?,?)");
                stmt.setString(1, order_code);
                stmt.setInt(2, customer_id);
                stmt.setString(3, myFormat.format(cal.getTime()));
                stmt.setDouble(4, final_total_price);
                stmt.executeUpdate();
            } catch (Exception e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "insert int orders db\n"+e);
            }

            //creating pdf 
            com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
            try {
                SimpleDateFormat myFormat = new SimpleDateFormat("dd-MM-yyyy");
                Calendar cal = Calendar.getInstance();
                PdfWriter.getInstance(doc, new FileOutputStream("C:\\\\Users\\Clark\\Desktop\\" + "" + order_code + ".pdf"));
                doc.open();
                Paragraph title = new Paragraph("                                                          El Mlouky factory");
                doc.add(title);
                Paragraph border = new Paragraph("\n----------------------------------------------------------------------------------------------------------------------\n");
                doc.add(border);
                Paragraph details = new Paragraph("\tEmployer: "+username+"\n"+"Customer: "+firstN_edt_txt.getText()+" "+lastN_edt_txt.getText()+"\n" +"Order Code: " + order_code + "\nDate: " + myFormat.format(cal.getTime()) + "\nTotal Paid: " + final_total_price);
                doc.add(details);
                doc.add(border);
                PdfPTable tbl = new PdfPTable(4);
                PdfPCell nameCell = new PdfPCell(new Phrase("Name"));
                PdfPCell priceCell = new PdfPCell(new Phrase("Price per unit"));
                PdfPCell quantityCell = new PdfPCell(new Phrase("Quantity"));
                PdfPCell totalCell = new PdfPCell(new Phrase("Price"));
                
                BaseColor backGroundColor = new BaseColor(213, 222, 239);
                nameCell.setBackgroundColor(backGroundColor);
                priceCell.setBackgroundColor(backGroundColor);
                quantityCell.setBackgroundColor(backGroundColor);
                totalCell.setBackgroundColor(backGroundColor);
                
                tbl.addCell(nameCell);
                tbl.addCell(priceCell);
                tbl.addCell(quantityCell);
                tbl.addCell(totalCell);
                
                for (int i = 0; i < cart_table.getRowCount(); i++) {
                    
                    tbl.addCell(cart_table.getValueAt(i, 1).toString());
                    tbl.addCell(cart_table.getValueAt(i, 3).toString());
                    tbl.addCell(cart_table.getValueAt(i, 2).toString());
                    tbl.addCell(cart_table.getValueAt(i, 4).toString());
                }
                doc.add(new Paragraph("\n"));
                doc.add(tbl);
                doc.add(border);
                Paragraph thanks = new Paragraph("\nThanks for your trust ,Please visit us again");
                doc.add(thanks);
                //doc.open();
                OpenPdf.openById(order_code);
                
            } catch (Exception e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(null, e);
            }
            
            doc.close();
            setVisible(false);
            new Orders(username).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a customer or some products");
            
        }
    }//GEN-LAST:event_order_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orders(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCart_btn;
    private javax.swing.JTextField address_edt_txt;
    private javax.swing.JButton back_btn;
    private javax.swing.JTable cart_table;
    private javax.swing.JTable cus_table;
    private javax.swing.JTextField firstN_edt_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lastN_edt_txt;
    private javax.swing.JButton order_btn;
    private javax.swing.JTextField ordersQuantity_edt_txt;
    private javax.swing.JTextField phNum_edt_txt;
    private javax.swing.JTextField price_edt_txt;
    private javax.swing.JTextField productName_edt_txt;
    private javax.swing.JTable product_table;
    private javax.swing.JTextField totAmount_edt_txt;
    private javax.swing.JButton viewOrders_btn;
    // End of variables declaration//GEN-END:variables
}
